server:
  port: 8080

  #eureka.instance.hostname指定了Eureka服务端的IP；
eureka:
  instance:
    hostname: localhost

  #是否向注册中心注册自己,由于自己就是服务器，不需要注册到自己
  client:
    register-with-eureka: false
    #是否获取注册表,由于自己就是服务器，不需要从服务器获取注册信息
    fetch-registry: false
    #eureka.client.serviceUrl.defaultZone指定Eureka服务端的地址，默认值为http://localhost:8761/eureka。
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/,http://localhost:8081/eureka/ #每个注册中心都需要吧自己注册到别的注册中心去
  server:
    eviction-interval-timer-in-ms: 2000  #剔除失效服务间隔