server:
  port: 8081

  #eureka.instance.hostname指定了Eureka服务端的IP；
eureka:
  instance:
    hostname: localhost
    #eureka.client.register-with-eureka表示是否将服务注册到Eureka服务端，由于自身就是Eureka服务端，所以设置为false；
    #register-with-eureka: true 配置高可用的时候需要开放自己注册自己，便于多个eureka注册中心互通
  client:
    register-with-eureka: false
    #eureka.client.fetch-registry表示是否从Eureka服务端获取服务信息，因为这里只搭建了一个Eureka服务端，并不需要从别的Eureka服务端同步服务信息，所以这里设置为false；
    fetch-registry: false
    #eureka.client.serviceUrl.defaultZone指定Eureka服务端的地址，默认值为http://localhost:8761/eureka。
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/,http://localhost:8080/eureka/

  server:
    eviction-interval-timer-in-ms: 2000  #剔除失效服务间隔