server:
  port: 8082

spring:
  application:
    name: Server-Provider

eureka:
  client:
    # 假设指定region为江苏
    region: js
    availability-zones:
      #假设江苏下面有南京的两个region
      js: nj2,nj1
    service-url:
      nj1: http://localhost:8080/eureka
      nj2: http://localhost:8081/eureka #注册中心地址
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
