server:
  port: 8081
spring:
  application:
    name: eureka-service
  #eureka.instance.hostname指定了Eureka服务端的IP
eureka:
  instance:
    hostname: localhost
    #register-with-eureka: true 配置高可用的时候需要开放自己注册自己，便于多个eureka注册中心互通
  client:
    register-with-eureka: true
    #eureka.client.fetch-registry表示是否从Eureka服务端获取服务信息
    fetch-registry: true
    #eureka.client.serviceUrl.defaultZone指定Eureka服务端的地址，默认值为http://localhost:8761/eureka。
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  server:
    eviction-interval-timer-in-ms: 2000  #剔除失效服务间隔